# SiliconFlow API Key (Required)
SILICONFLOW_API_KEY = "sk-lpmnkrmjecjryeruvsdrovodolqnjhsiohbjwgbinqllkomy"  # Replace with your actual API key

# Search Engine API Keys (Optional)
# Uncomment and fill in the ones you want to use
# YDC_API_KEY = "your-you-api-key"
# BING_SEARCH_API_KEY = "your-bing-api-key"
# BRAVE_API_KEY = "your-brave-api-key"
# SERPER_API_KEY = "your-serper-api-key"
# TAVILY_API_KEY = "your-tavily-api-key"
# SEARXNG_API_KEY = "your-searxng-api-key"

# HTTP Proxy (Optional)
# HTTP_PROXY = "your-proxy-url"

# Note: Copy this file to .streamlit/secrets.toml and replace with your actual API keys 